#Database configuration
#If you use BungeeCord please use MySql to synchronize the friend list over your network
#Modules: MySql, SQLite
module: SQLite
host: localhost
port: 3306
database: database
username: root
password: root
tableprefix: socialmanager_
